### ISSUE TITLE
'type' object is not subscriptable

### ISSUE THREAD

**Issue by aaronnewsome** [klipspringr/wordle-cli#2]
I followed the instructions for running this but I'm not able to. I'm using Python 3.8.10. When I clone the repo and run play.py, here's what I get:

```
$ ./play.py 
Traceback (most recent call last):
  File "./play.py", line 4, in <module>
    import wordle
  File "/home/anewsome/Desktop/1014-7555/wordle-cli/wordle.py", line 12, in <module>
    class Game:
  File "/home/anewsome/Desktop/1014-7555/wordle-cli/wordle.py", line 67, in Game
    def check_guess(guess: str, solution: str) -> list[LetterStates]:
TypeError: 'type' object is not subscriptable
```

I opened up the file to see if I could figure out what's really going on but I'm unable to figure it out. If anyone has a workaround, please post it!

**Comment by klipspringr** [comment]
Thanks for the report Aaron. It looks like

**Comment by klipspringr** [comment]
Thanks for the report, Aaron. It turns out the particular kind of type hinting used in that line was only introduced in Python 3.9. It should be a straightforward fix, I'll get something released shortly.

Annoyingly, I used a tool which detects the minimum required Python version and it reported 3.6 -- but it obviously missed this.

**Comment by aaronnewsome** [comment]
Thanks for looking into it. I was able to spin up a Windows VM with python 3.9 and it works as expected. Thanks for creating this, and the game play is great! I'm going to try a new Linux VM and try to get it running over an SSH connection.
